import type { ComponentType } from "react";
import type { JobCardProps } from "@/components/cards/JobCard";
import { MessagesSquare, Megaphone, Clapperboard, Code2, PenSquare, TrendingUp, UserSearch } from "lucide-react";

export interface Category {
  icon: ComponentType<{ className?: string }>;
  name: string;
  count: number;
  bgClass: string;
  textClass: string;
}

export const CATEGORIES_DATA: Category[] = [
  { icon: MessagesSquare, name: "Chat Management", count: 128, bgClass: "bg-primary-50", textClass: "text-primary-600" },
  { icon: Megaphone, name: "Marketing", count: 64, bgClass: "bg-warning-50", textClass: "text-warning-600" },
  { icon: Clapperboard, name: "Video Editing", count: 47, bgClass: "bg-danger-50", textClass: "text-danger-600" },
  { icon: Code2, name: "Development", count: 31, bgClass: "bg-success-50", textClass: "text-success-600" },
  { icon: PenSquare, name: "Copywriting", count: 22, bgClass: "bg-neutral-100", textClass: "text-neutral-600" },
  { icon: TrendingUp, name: "Sales & Growth", count: 18, bgClass: "bg-primary-50", textClass: "text-primary-600" },
  { icon: UserSearch, name: "Recruitment", count: 9, bgClass: "bg-warning-50", textClass: "text-warning-600" },
];

export type JobListing = Omit<JobCardProps, "onSaveToggle" | "onApply"> & { id: string; isPremium: boolean };

export const INITIAL_JOBS: JobListing[] = [
  // Chat Management
  {
    id: "job-1",
    title: "Chat Manager — OnlyFans Agency",
    type: "Full-time",
    timeAgo: "4 hrs ago",
    pay: "$6–9",
    paySuffix: "/hr",
    location: "Remote · Philippines",
    category: "Chat Management",
    isPremium: true,
    accentVariant: "primary",
  },
  {
    id: "job-2",
    title: "Fan Engagement Chatter",
    type: "Part-time",
    timeAgo: "6 hrs ago",
    pay: "$5–7",
    paySuffix: "/hr",
    location: "Remote · Worldwide",
    category: "Chat Management",
    isPremium: false,
    accentVariant: "primary",
  },
  {
    id: "job-3",
    title: "Senior Chat Team Lead",
    type: "Full-time",
    timeAgo: "3 days ago",
    pay: "$1,000",
    paySuffix: "/mo",
    location: "Remote · United States",
    category: "Chat Management",
    isPremium: true,
    accentVariant: "primary",
  },
  // Marketing
  {
    id: "job-4",
    title: "Social Media & Growth Manager",
    type: "Part-time",
    timeAgo: "2 days ago",
    pay: "$1,200",
    paySuffix: "/mo",
    location: "Remote · United States",
    category: "Marketing",
    isPremium: true,
    accentVariant: "warning",
  },
  {
    id: "job-5",
    title: "Content Marketing Specialist",
    type: "Contract",
    timeAgo: "5 hrs ago",
    pay: "$18–25",
    paySuffix: "/hr",
    location: "Remote · United Kingdom",
    category: "Marketing",
    isPremium: false,
    accentVariant: "warning",
  },
  // Video Editing
  {
    id: "job-6",
    title: "Reel & Short-Form Video Editor",
    type: "Contract",
    timeAgo: "1 day ago",
    pay: "10%",
    paySuffix: " commission",
    location: "Remote · Canada",
    category: "Video Editing",
    isPremium: false,
    accentVariant: "danger",
  },
  {
    id: "job-7",
    title: "Long-Form YouTube Editor",
    type: "Part-time",
    timeAgo: "8 hrs ago",
    pay: "$15–20",
    paySuffix: "/hr",
    location: "Remote · Worldwide",
    category: "Video Editing",
    isPremium: false,
    accentVariant: "danger",
  },
  {
    id: "job-8",
    title: "Motion Graphics Designer",
    type: "Full-time",
    timeAgo: "2 days ago",
    pay: "$2,000",
    paySuffix: "/mo",
    location: "Remote · Germany",
    category: "Video Editing",
    isPremium: true,
    accentVariant: "danger",
  },
  // Development
  {
    id: "job-9",
    title: "Full-Stack Developer",
    type: "Full-time",
    timeAgo: "12 hrs ago",
    pay: "$40–60",
    paySuffix: "/hr",
    location: "Remote · Worldwide",
    category: "Development",
    isPremium: true,
    accentVariant: "success",
  },
  {
    id: "job-10",
    title: "WordPress Developer",
    type: "Contract",
    timeAgo: "3 days ago",
    pay: "$20–30",
    paySuffix: "/hr",
    location: "Remote · India",
    category: "Development",
    isPremium: false,
    accentVariant: "success",
  },
  // Copywriting
  {
    id: "job-11",
    title: "SEO Copywriter",
    type: "Contract",
    timeAgo: "5 hrs ago",
    pay: "$0.10",
    paySuffix: "/word",
    location: "Remote · Worldwide",
    category: "Copywriting",
    isPremium: false,
    accentVariant: "primary",
  },
  {
    id: "job-12",
    title: "Email & Sales Copywriter",
    type: "Part-time",
    timeAgo: "1 day ago",
    pay: "$800",
    paySuffix: "/mo",
    location: "Remote · Australia",
    category: "Copywriting",
    isPremium: true,
    accentVariant: "primary",
  },
  // Sales & Growth
  {
    id: "job-13",
    title: "Outbound Sales Rep",
    type: "Full-time",
    timeAgo: "9 hrs ago",
    pay: "$15",
    paySuffix: "/hr + commission",
    location: "Remote · United States",
    category: "Sales & Growth",
    isPremium: true,
    accentVariant: "warning",
  },
  {
    id: "job-14",
    title: "Affiliate & Partnerships Manager",
    type: "Contract",
    timeAgo: "2 days ago",
    pay: "15%",
    paySuffix: " commission",
    location: "Remote · Worldwide",
    category: "Sales & Growth",
    isPremium: false,
    accentVariant: "warning",
  },
  // Recruitment
  {
    id: "job-15",
    title: "Talent Sourcer",
    type: "Part-time",
    timeAgo: "4 hrs ago",
    pay: "$10–14",
    paySuffix: "/hr",
    location: "Remote · Philippines",
    category: "Recruitment",
    isPremium: false,
    accentVariant: "danger",
  },
  {
    id: "job-16",
    title: "Senior Recruiter",
    type: "Full-time",
    timeAgo: "1 day ago",
    pay: "$1,800",
    paySuffix: "/mo",
    location: "Remote · United States",
    category: "Recruitment",
    isPremium: true,
    accentVariant: "danger",
  },
];
