export interface WorkerExperience {
  title: string;
  employer: string;
  period: string;
  duration: string;
  description: string;
}

export interface WorkerListing {
  id: string;
  name: string;
  avatarUrl: string;
  avatarInitial: string;
  avatarFrom: string;
  avatarTo: string;
  isVerified: boolean;
  countryCode: string | null;
  city: string;
  country: string;
  employmentType: string;
  languages: string[];
  languagesShort: string;
  topSkill: string;
  skillCategory: string;
  experienceYears: number;
  experienceLabel: string;
  intro: string;
  responseTimeLabel: string;
  joinedLabel: string;
  joinedHoursAgo: number;
  verifiedSkills: string[];
  selfReportedSkills: string[];
  experience: WorkerExperience[];
  phoneMasked: string;
  phone: string;
  emailMasked: string;
  email: string;
  software: string[];
  socialMedia: string[];
  paymentMethods: string[];
  gender: string;
}

export const EMPLOYMENT_TYPES = ["Full-time", "Part-time", "Contract"];
export const SKILL_CATEGORIES = ["Chatting", "Sales", "Copywriting", "Marketing", "Editing", "Recruitment", "General"];
export const SOFTWARE_OPTIONS = ["Chatting Tools", "CRM Platforms", "Scheduling Tools", "Design Tools"];
export const SOCIAL_MEDIA_OPTIONS = [
  "Instagram", "TikTok", "Twitter / X", "Threads", "YouTube",
  "Discord", "Telegram", "WhatsApp", "Reddit", "OnlyFans", "Fansly",
];
export const PAYMENT_OPTIONS = ["PayPal", "Wise", "Bank Transfer", "Crypto", "Payoneer"];
export const COUNTRY_OPTIONS = ["Philippines", "United States", "Nigeria", "India", "Kenya", "Brazil", "Mexico", "Germany", "Turkey"];
export const LANGUAGE_OPTIONS = ["English", "Tagalog", "French", "German", "Chinese", "Turkish", "Hindi", "Portuguese"];
export const GENDER_OPTIONS = ["Male", "Female", "Prefer not to say"];

export const WORKERS: WorkerListing[] = [
  {
    id: "maricel",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Maricel",
    avatarInitial: "M",
    avatarFrom: "#26BEFB",
    avatarTo: "#0090C7",
    isVerified: true,
    countryCode: "PH",
    city: "Manila",
    country: "Philippines",
    employmentType: "Full-time",
    languages: ["English", "Tagalog"],
    languagesShort: "EN/TL",
    topSkill: "Chatting",
    skillCategory: "Chatting",
    experienceYears: 3,
    experienceLabel: "3 Yrs",
    intro: "Friendly chat specialist who keeps fans engaged and coming back — 3 years managing DMs across multiple platforms.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 3 hours ago",
    joinedHoursAgo: 3,
    verifiedSkills: ["Chatting", "English (C1)"],
    selfReportedSkills: ["Sales", "Discord Moderation", "CRM Tools", "Tagalog (Native)"],
    experience: [
      { title: "Live Chat Agent", employer: "Nova Talent Agency", period: "Jan 2023 – Present", duration: "1 yr 8 mo", description: "Managed DM inboxes across Instagram and OnlyFans for 4 creators, maintaining response-time SLAs and driving PPV upsells through daily engagement." },
      { title: "Customer Support Rep", employer: "Bright Loop Studio", period: "Mar 2021 – Dec 2022", duration: "1 yr 10 mo", description: "Handled inbound support tickets and live chat for an e-commerce brand, averaging a 4.8/5 customer satisfaction score." },
      { title: "Community Moderator", employer: "Halo Creators Collective", period: "Jun 2020 – Feb 2021", duration: "9 mo", description: "Moderated a 12k-member Discord community, enforcing guidelines and escalating priority fan messages." },
      { title: "Data Entry Clerk", employer: "Freelance", period: "Sep 2019 – May 2020", duration: "9 mo", description: "Remote data entry and spreadsheet cleanup for small e-commerce sellers." },
    ],
    phoneMasked: "(4••) •••-••••",
    phone: "(405) 555-0128",
    emailMasked: "m••••••.•••••@••••••••.com",
    email: "maricel.delacruz@example.com",
    software: ["Chatting Tools", "CRM Platforms"],
    socialMedia: ["Instagram", "OnlyFans", "Discord"],
    paymentMethods: ["PayPal", "Payoneer"],
    gender: "Female",
  },
  {
    id: "jonas",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Jonas",
    avatarInitial: "J",
    avatarFrom: "#F59E0B",
    avatarTo: "#D97706",
    isVerified: false,
    countryCode: "DE",
    city: "Berlin",
    country: "Germany",
    employmentType: "Part-time",
    languages: ["German", "English"],
    languagesShort: "DE/EN",
    topSkill: "Editing",
    skillCategory: "Editing",
    experienceYears: 2,
    experienceLabel: "2 Yrs",
    intro: "Short-form editor with a sharp eye for hooks — I turn raw clips into scroll-stopping content.",
    responseTimeLabel: "Usually replies within a day",
    joinedLabel: "Joined 2 days ago",
    joinedHoursAgo: 48,
    verifiedSkills: ["Video Editing"],
    selfReportedSkills: ["Motion Graphics", "CapCut", "Premiere Pro"],
    experience: [
      { title: "Short-Form Video Editor", employer: "Meridian Fan Media", period: "Jun 2023 – Present", duration: "1 yr 5 mo", description: "Edited daily TikTok/Reels content for 6 creator accounts, averaging 40 clips a week." },
    ],
    phoneMasked: "(0••) •••-••••",
    phone: "(030) 555-0192",
    emailMasked: "j••••.•••••@••••••••.com",
    email: "jonas.weber@example.com",
    software: ["Design Tools"],
    socialMedia: ["TikTok", "Instagram"],
    paymentMethods: ["Wise", "Bank Transfer"],
    gender: "Male",
  },
  {
    id: "amara",
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Amara",
    avatarInitial: "A",
    avatarFrom: "#22C55E",
    avatarTo: "#16A34A",
    isVerified: true,
    countryCode: "NG",
    city: "Lagos",
    country: "Nigeria",
    employmentType: "Full-time",
    languages: ["English"],
    languagesShort: "EN",
    topSkill: "Sales",
    skillCategory: "Sales",
    experienceYears: 4,
    experienceLabel: "4 Yrs",
    intro: "Closer-minded sales chatter — I build genuine rapport first, then guide the conversation toward a yes.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined today",
    joinedHoursAgo: 0,
    verifiedSkills: ["Sales", "English (C2)"],
    selfReportedSkills: ["Negotiation", "Telegram"],
    experience: [
      { title: "Sales Closer — Fan Chatting", employer: "Kindred Media Group", period: "Feb 2022 – Present", duration: "2 yr 9 mo", description: "Drove PPV and subscription upsells across a roster of 3 creator accounts." },
      { title: "Telesales Agent", employer: "Palm & Co. Agency", period: "Jan 2020 – Jan 2022", duration: "2 yrs", description: "Outbound sales calls for a subscription products company." },
    ],
    phoneMasked: "(7••) •••-••••",
    phone: "(701) 555-0143",
    emailMasked: "a•••••.•••••@••••••••.com",
    email: "amara.okafor@example.com",
    software: ["CRM Platforms"],
    socialMedia: ["Telegram", "WhatsApp"],
    paymentMethods: ["Crypto", "PayPal"],
    gender: "Female",
  },
  {
    id: "rafael",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Rafael",
    avatarInitial: "R",
    avatarFrom: "#7C8A92",
    avatarTo: "#414D54",
    isVerified: false,
    countryCode: "BR",
    city: "São Paulo",
    country: "Brazil",
    employmentType: "Part-time",
    languages: ["Portuguese", "English"],
    languagesShort: "PT/EN",
    topSkill: "General",
    skillCategory: "General",
    experienceYears: 1,
    experienceLabel: "1 Yr",
    intro: "Detail-oriented virtual assistant — scheduling, inbox management, and admin busywork, handled.",
    responseTimeLabel: "Usually replies within a day",
    joinedLabel: "Joined 5 hours ago",
    joinedHoursAgo: 5,
    verifiedSkills: ["English (B2)"],
    selfReportedSkills: ["Scheduling", "Google Workspace", "Notion"],
    experience: [
      { title: "Virtual Assistant", employer: "Crestline Agency Group", period: "Oct 2024 – Present", duration: "10 mo", description: "Managed calendars, inbox triage, and light bookkeeping for two agency accounts." },
    ],
    phoneMasked: "(2••) •••-••••",
    phone: "(212) 555-0184",
    emailMasked: "r•••••.•••••@••••••••.com",
    email: "rafael.souza@example.com",
    software: ["Scheduling Tools"],
    socialMedia: ["WhatsApp", "Discord"],
    paymentMethods: ["Bank Transfer", "PayPal"],
    gender: "Male",
  },
  {
    id: "selin",
    avatarUrl: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Selin",
    avatarInitial: "S",
    avatarFrom: "#EF4444",
    avatarTo: "#DC2626",
    isVerified: true,
    countryCode: "TR",
    city: "Istanbul",
    country: "Turkey",
    employmentType: "Contract",
    languages: ["Turkish", "English"],
    languagesShort: "TR/EN",
    topSkill: "Copywriting",
    skillCategory: "Copywriting",
    experienceYears: 3,
    experienceLabel: "3 Yrs",
    intro: "Copywriter with a direct-response background — I write DMs and captions that get replies, not just likes.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 1 day ago",
    joinedHoursAgo: 24,
    verifiedSkills: ["Copywriting"],
    selfReportedSkills: ["Email Marketing", "A/B Testing"],
    experience: [
      { title: "Direct-Response Copywriter", employer: "Halo Creators Collective", period: "May 2022 – Present", duration: "2 yr 6 mo", description: "Wrote PPV captions and DM scripts across 5 creator accounts." },
    ],
    phoneMasked: "(5••) •••-••••",
    phone: "(551) 555-0117",
    emailMasked: "s•••••.•••••@••••••••.com",
    email: "selin.yildiz@example.com",
    software: ["Design Tools"],
    socialMedia: ["Instagram", "Twitter / X"],
    paymentMethods: ["Payoneer", "Wise"],
    gender: "Female",
  },
  {
    id: "priya",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Priya",
    avatarInitial: "P",
    avatarFrom: "#26BEFB",
    avatarTo: "#0090C7",
    isVerified: true,
    countryCode: "IN",
    city: "Mumbai",
    country: "India",
    employmentType: "Full-time",
    languages: ["English", "Hindi"],
    languagesShort: "EN/HI",
    topSkill: "Recruitment",
    skillCategory: "Recruitment",
    experienceYears: 5,
    experienceLabel: "5 Yrs",
    intro: "Recruitment specialist who's screened and placed 200+ chatters and closers over the last two years.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 8 hours ago",
    joinedHoursAgo: 8,
    verifiedSkills: ["Recruitment", "English (C1)"],
    selfReportedSkills: ["Interviewing", "ATS Tools"],
    experience: [
      { title: "Talent Recruitment Specialist", employer: "Redstar Talent Partners", period: "Sep 2021 – Present", duration: "3 yr 2 mo", description: "Sourced, screened, and onboarded remote chatters and closers for 12+ agencies." },
      { title: "HR Coordinator", employer: "Lumen Digital Talent", period: "Jul 2019 – Aug 2021", duration: "2 yrs 2 mo", description: "Ran full-cycle recruitment for a remote customer support team." },
    ],
    phoneMasked: "(9••) •••-••••",
    phone: "(917) 555-0166",
    emailMasked: "p•••••.•••••@••••••••.com",
    email: "priya.sharma@example.com",
    software: ["CRM Platforms"],
    socialMedia: ["Instagram", "Telegram"],
    paymentMethods: ["PayPal", "Bank Transfer"],
    gender: "Female",
  },
  {
    id: "redi",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Maricel",
    avatarInitial: "M",
    avatarFrom: "#26BEFB",
    avatarTo: "#0090C7",
    isVerified: true,
    countryCode: "PH",
    city: "Manila",
    country: "Philippines",
    employmentType: "Full-time",
    languages: ["English", "Tagalog"],
    languagesShort: "EN/TL",
    topSkill: "Chatting",
    skillCategory: "Chatting",
    experienceYears: 3,
    experienceLabel: "3 Yrs",
    intro: "Friendly chat specialist who keeps fans engaged and coming back — 3 years managing DMs across multiple platforms.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 3 hours ago",
    joinedHoursAgo: 3,
    verifiedSkills: ["Chatting", "English (C1)"],
    selfReportedSkills: ["Sales", "Discord Moderation", "CRM Tools", "Tagalog (Native)"],
    experience: [
      { title: "Live Chat Agent", employer: "Nova Talent Agency", period: "Jan 2023 – Present", duration: "1 yr 8 mo", description: "Managed DM inboxes across Instagram and OnlyFans for 4 creators, maintaining response-time SLAs and driving PPV upsells through daily engagement." },
      { title: "Customer Support Rep", employer: "Bright Loop Studio", period: "Mar 2021 – Dec 2022", duration: "1 yr 10 mo", description: "Handled inbound support tickets and live chat for an e-commerce brand, averaging a 4.8/5 customer satisfaction score." },
      { title: "Community Moderator", employer: "Halo Creators Collective", period: "Jun 2020 – Feb 2021", duration: "9 mo", description: "Moderated a 12k-member Discord community, enforcing guidelines and escalating priority fan messages." },
      { title: "Data Entry Clerk", employer: "Freelance", period: "Sep 2019 – May 2020", duration: "9 mo", description: "Remote data entry and spreadsheet cleanup for small e-commerce sellers." },
    ],
    phoneMasked: "(4••) •••-••••",
    phone: "(405) 555-0128",
    emailMasked: "m••••••.•••••@••••••••.com",
    email: "maricel.delacruz@example.com",
    software: ["Chatting Tools", "CRM Platforms"],
    socialMedia: ["Instagram", "OnlyFans", "Discord"],
    paymentMethods: ["PayPal", "Payoneer"],
    gender: "Female",
  },
  {
    id: "pedi",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Jonas",
    avatarInitial: "J",
    avatarFrom: "#F59E0B",
    avatarTo: "#D97706",
    isVerified: false,
    countryCode: "DE",
    city: "Berlin",
    country: "Germany",
    employmentType: "Part-time",
    languages: ["German", "English"],
    languagesShort: "DE/EN",
    topSkill: "Editing",
    skillCategory: "Editing",
    experienceYears: 2,
    experienceLabel: "2 Yrs",
    intro: "Short-form editor with a sharp eye for hooks — I turn raw clips into scroll-stopping content.",
    responseTimeLabel: "Usually replies within a day",
    joinedLabel: "Joined 2 days ago",
    joinedHoursAgo: 48,
    verifiedSkills: ["Video Editing"],
    selfReportedSkills: ["Motion Graphics", "CapCut", "Premiere Pro"],
    experience: [
      { title: "Short-Form Video Editor", employer: "Meridian Fan Media", period: "Jun 2023 – Present", duration: "1 yr 5 mo", description: "Edited daily TikTok/Reels content for 6 creator accounts, averaging 40 clips a week." },
    ],
    phoneMasked: "(0••) •••-••••",
    phone: "(030) 555-0192",
    emailMasked: "j••••.•••••@••••••••.com",
    email: "jonas.weber@example.com",
    software: ["Design Tools"],
    socialMedia: ["TikTok", "Instagram"],
    paymentMethods: ["Wise", "Bank Transfer"],
    gender: "Male",
  },
  {
    id: "medi",
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Amara",
    avatarInitial: "A",
    avatarFrom: "#22C55E",
    avatarTo: "#16A34A",
    isVerified: true,
    countryCode: "NG",
    city: "Lagos",
    country: "Nigeria",
    employmentType: "Full-time",
    languages: ["English"],
    languagesShort: "EN",
    topSkill: "Sales",
    skillCategory: "Sales",
    experienceYears: 4,
    experienceLabel: "4 Yrs",
    intro: "Closer-minded sales chatter — I build genuine rapport first, then guide the conversation toward a yes.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined today",
    joinedHoursAgo: 0,
    verifiedSkills: ["Sales", "English (C2)"],
    selfReportedSkills: ["Negotiation", "Telegram"],
    experience: [
      { title: "Sales Closer — Fan Chatting", employer: "Kindred Media Group", period: "Feb 2022 – Present", duration: "2 yr 9 mo", description: "Drove PPV and subscription upsells across a roster of 3 creator accounts." },
      { title: "Telesales Agent", employer: "Palm & Co. Agency", period: "Jan 2020 – Jan 2022", duration: "2 yrs", description: "Outbound sales calls for a subscription products company." },
    ],
    phoneMasked: "(7••) •••-••••",
    phone: "(701) 555-0143",
    emailMasked: "a•••••.•••••@••••••••.com",
    email: "amara.okafor@example.com",
    software: ["CRM Platforms"],
    socialMedia: ["Telegram", "WhatsApp"],
    paymentMethods: ["Crypto", "PayPal"],
    gender: "Female",
  },
  {
    id: "shano",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Rafael",
    avatarInitial: "R",
    avatarFrom: "#7C8A92",
    avatarTo: "#414D54",
    isVerified: false,
    countryCode: "BR",
    city: "São Paulo",
    country: "Brazil",
    employmentType: "Part-time",
    languages: ["Portuguese", "English"],
    languagesShort: "PT/EN",
    topSkill: "General",
    skillCategory: "General",
    experienceYears: 1,
    experienceLabel: "1 Yr",
    intro: "Detail-oriented virtual assistant — scheduling, inbox management, and admin busywork, handled.",
    responseTimeLabel: "Usually replies within a day",
    joinedLabel: "Joined 5 hours ago",
    joinedHoursAgo: 5,
    verifiedSkills: ["English (B2)"],
    selfReportedSkills: ["Scheduling", "Google Workspace", "Notion"],
    experience: [
      { title: "Virtual Assistant", employer: "Crestline Agency Group", period: "Oct 2024 – Present", duration: "10 mo", description: "Managed calendars, inbox triage, and light bookkeeping for two agency accounts." },
    ],
    phoneMasked: "(2••) •••-••••",
    phone: "(212) 555-0184",
    emailMasked: "r•••••.•••••@••••••••.com",
    email: "rafael.souza@example.com",
    software: ["Scheduling Tools"],
    socialMedia: ["WhatsApp", "Discord"],
    paymentMethods: ["Bank Transfer", "PayPal"],
    gender: "Male",
  },
  {
    id: "dhano",
    avatarUrl: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Selin",
    avatarInitial: "S",
    avatarFrom: "#EF4444",
    avatarTo: "#DC2626",
    isVerified: true,
    countryCode: "TR",
    city: "Istanbul",
    country: "Turkey",
    employmentType: "Contract",
    languages: ["Turkish", "English"],
    languagesShort: "TR/EN",
    topSkill: "Copywriting",
    skillCategory: "Copywriting",
    experienceYears: 3,
    experienceLabel: "3 Yrs",
    intro: "Copywriter with a direct-response background — I write DMs and captions that get replies, not just likes.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 1 day ago",
    joinedHoursAgo: 24,
    verifiedSkills: ["Copywriting"],
    selfReportedSkills: ["Email Marketing", "A/B Testing"],
    experience: [
      { title: "Direct-Response Copywriter", employer: "Halo Creators Collective", period: "May 2022 – Present", duration: "2 yr 6 mo", description: "Wrote PPV captions and DM scripts across 5 creator accounts." },
    ],
    phoneMasked: "(5••) •••-••••",
    phone: "(551) 555-0117",
    emailMasked: "s•••••.•••••@••••••••.com",
    email: "selin.yildiz@example.com",
    software: ["Design Tools"],
    socialMedia: ["Instagram", "Twitter / X"],
    paymentMethods: ["Payoneer", "Wise"],
    gender: "Female",
  },
  {
    id: "rajpal",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop&crop=faces&auto=format&q=80",
    name: "Priya",
    avatarInitial: "P",
    avatarFrom: "#26BEFB",
    avatarTo: "#0090C7",
    isVerified: true,
    countryCode: "IN",
    city: "Mumbai",
    country: "India",
    employmentType: "Full-time",
    languages: ["English", "Hindi"],
    languagesShort: "EN/HI",
    topSkill: "Recruitment",
    skillCategory: "Recruitment",
    experienceYears: 5,
    experienceLabel: "5 Yrs",
    intro: "Recruitment specialist who's screened and placed 200+ chatters and closers over the last two years.",
    responseTimeLabel: "Usually replies within a few hours",
    joinedLabel: "Joined 8 hours ago",
    joinedHoursAgo: 8,
    verifiedSkills: ["Recruitment", "English (C1)"],
    selfReportedSkills: ["Interviewing", "ATS Tools"],
    experience: [
      { title: "Talent Recruitment Specialist", employer: "Redstar Talent Partners", period: "Sep 2021 – Present", duration: "3 yr 2 mo", description: "Sourced, screened, and onboarded remote chatters and closers for 12+ agencies." },
      { title: "HR Coordinator", employer: "Lumen Digital Talent", period: "Jul 2019 – Aug 2021", duration: "2 yrs 2 mo", description: "Ran full-cycle recruitment for a remote customer support team." },
    ],
    phoneMasked: "(9••) •••-••••",
    phone: "(917) 555-0166",
    emailMasked: "p•••••.•••••@••••••••.com",
    email: "priya.sharma@example.com",
    software: ["CRM Platforms"],
    socialMedia: ["Instagram", "Telegram"],
    paymentMethods: ["PayPal", "Bank Transfer"],
    gender: "Female",
  },
];

export function getWorkerById(id: string): WorkerListing | undefined {
  return WORKERS.find((w) => w.id === id);
}

export function getSimilarWorkers(worker: WorkerListing, limit = 6): WorkerListing[] {
  return WORKERS.filter((w) => w.id !== worker.id && w.skillCategory === worker.skillCategory)
    .concat(WORKERS.filter((w) => w.id !== worker.id && w.skillCategory !== worker.skillCategory))
    .slice(0, limit);
}

export const TOTAL_WORKER_COUNT = WORKERS.length;
